services:
  - type: web
    name: bitespeed-backend
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 3000
      # Add database connection vars (Render provides these automatically)
      - key: PG_HOST
        value: ${bitespeed-db.internalHost}
      - key: PG_USER
        value: ${bitespeed-db.user}
      - key: PG_PASSWORD
        value: ${bitespeed-db.password}
      - key: PG_DATABASE
        value: ${bitespeed-db.database} # Use just the database name, not full connection string
      - key: PG_PORT
        value: ${bitespeed-db.internalPort}
databases:
  - name: bitespeed-db
    databaseName: bitespeed
    user: bitespeed_user
    plan: free
