# render.yaml
services:
  - type: web
    name: bitespeed-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
      - key: NODE_ENV
        value: production
databases:
  - name: bitespeed-db
    databaseName: bitespeed
    user: bitespeed_user
    plan: free  # Use "free" for testing, "standard" for production